### ISSUE TITLE
Docker image doesn't start

### ISSUE THREAD

**Issue by fasolens** [OpenTMI/opentmi#111] opened 2017-10-11 09:17 UTC
### Description
- Type: Bug
Docker container does not start.

---------------------------------------------------------------
## Bug

**opentmi version**
```
npm info lifecycle OpenTMI@0.4.2~prestart: OpenTMI@0.4.2
npm info lifecycle OpenTMI@0.4.2~start: OpenTMI@0.4.2
```

**node.js version**
```
npm info using npm@3.10.10
npm info using node@v6.11.4
```

**Expected Behavior**
run opentmi docker

**Actual Behavior**
opentmi docker exit with error

**Steps to Reproduce**
1. docker pull mongo:latest
2. docker pull opentmi/opentmi:latest
3. docker run -v "$(pwd)":/data --name mongo -d mongo mongod --smallfiles
4. docker run --name opentmi -p 3000:3000 --link mongo:mongo opentmi/opentmi

Docker output:

```
root@host12:~/opentmi/data# docker run --name opentmi -p 3000:3000 --link mongo:mongo  opentmi/opentmi
npm info it worked if it ends with ok
npm info using npm@3.10.10
npm info using node@v6.11.4
npm info lifecycle OpenTMI@0.4.2~prestart: OpenTMI@0.4.2
npm info lifecycle OpenTMI@0.4.2~start: OpenTMI@0.4.2

> OpenTMI@0.4.2 start /usr/src/app
> node index.js "-v"

debug: Using cfg: development.
info: <Master> 17 is running
info: <Master> Start forking 8 workers..
warn: <Master> Master process exited with error code: 1.
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/usr/src/app/log/app.log.2017-10-11'
    at Error (native)

npm info lifecycle OpenTMI@0.4.2~start: Failed to exec start script
npm ERR! Linux 4.4.0-83-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start" "--" "-v"
npm ERR! node v6.11.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! OpenTMI@0.4.2 start: `node index.js "-v"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the OpenTMI@0.4.2 start script 'node index.js "-v"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the OpenTMI package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js "-v"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs OpenTMI
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls OpenTMI
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/app/npm-debug.log
```

**Comment by jupe** [comment] 2017-10-11 18:13
hmm, have to try docker also from registry.. somehow it cannot see log -folder but not yet sure why... more verbose logs would help a bit..

**Comment by jupe** [comment] 2017-10-11 18:38
I can reproduce this also so should be able to fix it soon :)

**Comment by jupe** [comment] 2017-10-11 19:31
found reason: docker COPY copies only files and probably ignore `.gitignore` by default -> it never copy log folder to image and that why it throws - application doesn’t create log folder if it not exists. This should be easy to fix when I’ve a bit more time.  PR for this is more than welcome ;)

**Comment by jupe** [comment] 2017-10-14 06:25
could you try with latest release @fasolens ?

**Comment by fasolens** [comment] 2017-10-17 07:40
Hi, I don't have access to the machine where I found the issue but I have clean system (archlinux) with docker.
The docker output is:
```
$ docker run --name opentmi -p 3000:3000 --link mongo:mongo opentmi/opentmi
npm info it worked if it ends with ok
npm info using npm@3.10.10
npm info using node@v6.11.4
npm info lifecycle OpenTMI@0.5.0~prestart: OpenTMI@0.5.0
npm info lifecycle OpenTMI@0.5.0~start: OpenTMI@0.5.0

> OpenTMI@0.5.0 start /usr/src/app
> node index.js "-v"

fs.js:924
  return binding.mkdir(pathModule._makeLong(path),
                 ^

Error: ENOENT: no such file or directory, mkdir '/usr/src/app/log/app.log'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:924:18)
    at Object.<anonymous> (/usr/src/app/app/tools/logger.js:22:6)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

npm info lifecycle OpenTMI@0.5.0~start: Failed to exec start script
npm ERR! Linux 4.13.5-1-MANJARO
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start" "--" "-v"
npm ERR! node v6.11.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! OpenTMI@0.5.0 start: `node index.js "-v"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the OpenTMI@0.5.0 start script 'node index.js "-v"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the OpenTMI package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js "-v"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs OpenTMI
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls OpenTMI
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/app/npm-debug.log
```
I will do more debuging and check the error. I will update soon.

**Comment by jupe** [comment] 2017-10-17 07:56
it sounds that there is still something wrong, reopening..

**Comment by jupe** [comment] 2017-10-17 08:02
See #121 - hope that it finally solves this :)

**Comment by fasolens** [comment] 2017-10-17 08:08
Docker is updated automatically? 
When should I test this?

**Comment by jupe** [comment] 2017-10-17 09:49
> Docker is updated automatically?
Only for releases at the moment. I tried to change configuration to build also from this fix branch but seems that I somehow lose access to do it

> When should I test this?
Could you try build it by your self ?

**Comment by jupe** [comment] 2017-10-17 09:56
I verified #121 by myself. It will fix log folder creation issue finally :)

**Comment by jupe** [comment] 2017-10-17 12:01
I'll close this one more time - since it should be working now with v0.5.1. Docker is compiled automatically and should be there soon: https://hub.docker.com/r/opentmi/opentmi/tags/ . If there is any other issues please raise new ticket / add comments here.

**Closed** 2017-10-17 19:39 UTC
Labels: bug
