### ISSUE TITLE
Testcase updating fails

### ISSUE THREAD

**Issue by onttoni** [OpenTMI/opentmi#68] opened 2017-08-17 08:05 UTC
### Description
I'm trying to update a testcase trough api. The update fails with:
```
Aug 17 07:55:44 ip-10-10-74-194 opentmi[9159]:       throw er; // Unhandled 'error' event
Aug 17 07:55:44 ip-10-10-74-194 opentmi[9159]:       ^
Aug 17 07:55:44 ip-10-10-74-194 opentmi[9159]: TypeError: Cannot read property 'toObject' of null
Aug 17 07:55:44 ip-10-10-74-194 opentmi[9159]:     at _model.findByIdAndUpdate (/home/ubuntu/git/opentmi/app/controllers/index.js:98:32)
Aug 17 07:55:44 ip-10-10-74-194 opentmi[9159]:     at /home/ubuntu/git/opentmi/node_modules/mongoose/lib/model.js:3822:16
Aug 17 07:55:44 ip-10-10-74-194 opentmi[9159]:     at Query.<anonymous> (/home/ubuntu/git/opentmi/node_modules/mongoose/lib/model.js:3822:16)
Aug 17 07:55:44 ip-10-10-74-194 opentmi[9159]:     at /home/ubuntu/git/opentmi/node_modules/kareem/index.js:273:21
Aug 17 07:55:44 ip-10-10-74-194 opentmi[9159]:     at /home/ubuntu/git/opentmi/node_modules/kareem/index.js:131:16
Aug 17 07:55:44 ip-10-10-74-194 opentmi[9159]:     at _combinedTickCallback (internal/process/next_tick.js:73:7)
Aug 17 07:55:44 ip-10-10-74-194 opentmi[9159]:     at process._tickCallback (internal/process/next_tick.js:104:9)
Aug 17 07:55:44 ip-10-10-74-194 systemd[1]: opentmi.service: Main process exited, code=exited, status=1/FAILURE
Aug 17 07:55:44 ip-10-10-74-194 systemd[1]: opentmi.service: Unit entered failed state.
Aug 17 07:55:44 ip-10-10-74-194 systemd[1]: opentmi.service: Failed with result 'exit-code'.
```

Model name in req.params is not with uppercase first letter, but this.modelName used on https://github.com/OpenTMI/opentmi/blob/c2c69405fe5c3e1fa919a438a7ac1ff062262d5b/app/controllers/index.js#L93 when accessing req.params has value with uppercase first letter.

---------------------------------------------------------------
## Bug

**opentmi version**
git describe --tags
v0.3.0

**node.js version**
node -v&&node -p process.versions.v8
v6.10.3
5.1.281.101

**Expected Behavior**
Updating testcase works without TypeError.

**Actual Behavior**
Testcase update fails with TypeError.

**Comment by olkorhon** [comment] 2017-08-17 08:40
This was caused by a bug in the testcase router, see the pr linked below for more information.
Fixed by: https://github.com/OpenTMI/opentmi/pull/69

**Closed** 2017-08-18 11:32 UTC
Labels: bug
